# Generated by Django 4.1.1 on 2023-01-18 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("waste", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="waste", old_name="sender", new_name="user",),
    ]
