# Generated by Django 4.1.1 on 2023-01-18 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("App_Login", "0005_slider"),
        ("waste", "0002_rename_sender_waste_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waste",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="App_Login.profile"
            ),
        ),
    ]
