# Generated by Django 4.1.5 on 2023-01-18 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("App_Login", "0005_slider"),
        ("waste", "0004_alter_waste_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="waste",
            name="title",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="waste",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="App_Login.profile"
            ),
        ),
    ]
