# Generated by Django 4.1.5 on 2023-01-21 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("waste", "0008_alter_waste_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waste", name="pincode", field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name="waste",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_sender",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
