# Generated by Django 4.1.1 on 2023-01-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_Login", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(blank=True, upload_to="profile_pic"),
        ),
        migrations.AddField(
            model_name="profile",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("FARMER", "FARMER"),
                    ("AGRONOMISTS", "AGRONOMISTS"),
                    ("FOR_WASTE", "FOR_WASTE"),
                    ("SELLER", "SELLER"),
                ],
                default="FARMER",
                max_length=40,
            ),
        ),
    ]
