# Generated by Django 4.1.1 on 2023-01-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_Login", "0002_profile_profile_pic_profile_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designate whether this user should be treatea as active",
                verbose_name="active",
            ),
        ),
    ]
